import { readdir, readFile, watch, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const postsDir = path.join(rootDir, 'posts');
const outputFile = path.join(rootDir, 'js', 'posts.js');
const watchMode = process.argv.includes('--watch');

function splitParagraphs(text) {
  return text
    .trim()
    .split(/\n\s*\n/)
    .map((paragraph) => paragraph.replace(/\r/g, '').trim())
    .filter(Boolean);
}

function parseFrontmatter(markdown) {
  const match = markdown.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) {
    return { metadata: {}, bodyText: markdown.trim() };
  }

  const [, frontmatterText, bodyText] = match;
  const metadata = {};

  for (const rawLine of frontmatterText.split('\n')) {
    const line = rawLine.trim();
    if (!line) continue;

    const separatorIndex = line.indexOf(':');
    if (separatorIndex === -1) continue;

    const key = line.slice(0, separatorIndex).trim();
    const value = line.slice(separatorIndex + 1).trim();
    metadata[key] = value;
  }

  return { metadata, bodyText: bodyText.trim() };
}

function titleFromFilename(filename) {
  return path
    .basename(filename, '.md')
    .replace(/^\d{4}-\d{2}-\d{2}-/, '')
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (char) => char.toUpperCase())
    .trim();
}

function parseWrittenDate(value) {
  const match = String(value).match(/^(\d{2})-(\d{2})-(\d{4})$/);
  if (!match) {
    return null;
  }

  const [, day, month, year] = match;
  const date = new Date(`${year}-${month}-${day}T00:00:00`);
  return Number.isNaN(date.getTime()) ? null : date;
}

async function buildPosts() {
  const files = (await readdir(postsDir))
    .filter((file) => file.endsWith('.md') && !file.startsWith('_'))
    .sort();

  const posts = [];

  for (const file of files) {
    const markdown = await readFile(path.join(postsDir, file), 'utf8');
    const { metadata, bodyText } = parseFrontmatter(markdown);
    const title = metadata.title || titleFromFilename(file);
    const written = metadata.written || '';
    const writtenDate = parseWrittenDate(written);

    posts.push({
      title,
      written,
      body: splitParagraphs(bodyText),
      sortValue: writtenDate ? writtenDate.getTime() : 0,
    });
  }

  posts.sort((a, b) => a.sortValue - b.sortValue || a.title.localeCompare(b.title));

  const browserPosts = posts.map(({ sortValue, ...post }) => post);
  const output = `// Generated by scripts/build-posts.mjs\nwindow.X13N_POSTS = ${JSON.stringify(browserPosts, null, 2)};\n`;

  await writeFile(outputFile, output, 'utf8');
  console.log(`[${new Date().toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit', second: '2-digit' })}] Built ${browserPosts.length} posts into js/posts.js`);
}

async function run() {
  await buildPosts();

  if (!watchMode) {
    return;
  }

  console.log('Watching posts/ for changes...');

  let rebuildTimer;
  for await (const event of watch(postsDir)) {
    if (!event.filename || !String(event.filename).endsWith('.md')) {
      continue;
    }

    clearTimeout(rebuildTimer);
    rebuildTimer = setTimeout(() => {
      buildPosts().catch((error) => {
        console.error('Build failed:', error.message);
      });
    }, 120);
  }
}

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
